language: node_js
node_js:
  - "12"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master