// Recipes
export const recipesConstants = {
    REQUEST_RECIPE: 'REQUEST_RECIPE',
    CREATE_RECIPE: 'CREATE_RECIPE',
    CREATE_RECIPE_SUCCESS: 'CREATE_RECIPE_SUCCESS',
    CREATE_RECIPE_ERROR: 'CREATE_RECIPE_ERROR',

    GET_RECIPE: 'GET_RECIPE',
    GET_RECIPE_SUCCESS: 'GET_RECIPE_SUCCESS',
    GET_RECIPE_ERROR: 'GET_RECIPE_ERROR',

    GET_RECIPES: 'GET_RECIPES',
    GET_RECIPES_SUCCESS: 'GET_RECIPES_SUCCESS',
    GET_RECIPES_ERROR: 'GET_RECIPES_ERROR',
    GET_DAILY_RECIPE_SUCCESS: 'GET_DAILY_RECIPE_SUCCESS',
    GET_DAILY_RECIPE_FAILLURE: 'GET_DAILY_RECIPE_FAILLURE'

} 

export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    GET_USER_SUCCESS: 'GET_USER_SUCCESS',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE'
} 

export const categoryConstants = {
    REQUEST_CATEGORY: 'REQUEST_CATEGORY',
    CREATE_CATEGORY: 'CREATE_CATEGORY',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_ERROR: 'CREATE_CATEGORY_ERROR',

    GETALL_REQUEST: 'CATEGORIES_GETALL_REQUEST',
    GETALL_SUCCESS: 'CATEGORIES_GETALL_SUCCESS',
    GETALL_FAILURE: 'CATEGORIES_GETALL_FAILURE',

    DELETE_REQUEST: 'CATEGORY_DELETE_REQUEST',
    DELETE_SUCCESS: 'CATEGORY_DELETE_SUCCESS',
    DELETE_FAILURE: 'CATEGORY_DELETE_FAILURE'
} 

export const ingredientConstants = {
    REQUEST_INGREDIENT: 'REQUEST_INGREDIENT',
    CREATE_INGREDIENT: 'CREATE_INGREDIENT',
    CREATE_INGREDIENT_SUCCESS: 'CREATE_INGREDIENT_SUCCESS',
    CREATE_INGREDIENT_ERROR: 'CREATE_INGREDIENT_ERROR',

    GETALL_REQUEST: 'INGREDIENTS_GETALL_REQUEST',
    GETALL_SUCCESS: 'INGREDIENTS_GETALL_SUCCESS',
    GETALL_FAILURE: 'INGREDIENTS_GETALL_FAILURE',

    DELETE_REQUEST: 'INGREDIENT_DELETE_REQUEST',
    DELETE_SUCCESS: 'INGREDIENT_DELETE_SUCCESS',
    DELETE_FAILURE: 'INGREDIENT_DELETE_FAILURE'
} 